// import Icons
import 'bootstrap-icons/font/bootstrap-icons.css';

// import bootstrap
import 'bootstrap/dist/css/bootstrap.css';

// import aos css
import 'aos/dist/aos.css';

import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google"; 

import Header from '@/components/Header'; // Ensure the path is correct

import './variables.css';
import "./globals.css";

// Importing EB Garamond font
const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-eb-garamond", // Ensure this matches your CSS variable naming
});

export const metadata: Metadata = {
  title: "Digital News Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ebGaramond.variable}`}> {/* Use ebGaramond here */}
        <Header /> {/* Ensure Header component path is correct */}
        {children}
      </body>
    </html>
  );
}
